name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Create env file
        run: |
          touch .env
          echo NEXT_PUBLIC_NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
          echo KEYCLOAK_ID=${{ secrets.KEYCLOAK_ID }} >> .env
          echo KEYCLOAK_SECRET=${{ secrets.KEYCLOAK_SECRET }} >> .env
          echo KEYCLOAK_ISSUER=${{ secrets.KEYCLOAK_ISSUER }} >> .env
          cat .env

      - name: Install dependencies
        run: yarn install

      - name: Build static file
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

#      - name: Deploy static site to S3 bucket
#        run: aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete

#      - name: Invalidating cloudfront distribution
#        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
